sudo: required

# attempt to get rid of the bundle install
language: php

services:
  - docker

env:
  global:
    - RAILS_ENV: test
    # DOCKER_COMPOSE_VERSION: 1.7
    - DOCKER_COMPOSE_VERSION: 1.4.2

before_script:
  - docker/install_docker-compose.sh

script:
  - docker-compose up -e "RAILS_ENV=test"
  - RAILS_ENV=test docker-compose run -e "RAILS_ENV=test" web rake db:create db:migrate
  - docker-compose run -e "RAILS_ENV=test" web bundle exec rspec
