sudo: required

services:
  - docker

env:
  # DOCKER_COMPOSE_VERSION: 1.7
  - DOCKER_COMPOSE_VERSION: 1.4.2
  RAILS_ENV=test

before_script:
  - docker/install_docker-compose.sh

script:
  # - docker build .
  - docker-compose up
  - RAILS_ENV=test docker-compose run -e "RAILS_ENV=test" web rake db:create db:migrate
  - docker-compose run -e "RAILS_ENV=test" web bundle exec rspec
