sudo: required

services:
  - docker

env:
  # DOCKER_COMPOSE_VERSION: 1.7
  DOCKER_COMPOSE_VERSION: 1.4.2

before_script:
  - docker/install_docker-compose.sh

script:
  - docker build .
  - docker-compose up
  - docker-compose run web RAILS_ENV=test rake db:create db:migrate
  - docker-compose run web bundle exec rspec
