db:
  image: mysql
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD="true"

web:
  build: .
  command: bash -c 'rake db:create && rake db:migrate && [[ "$RAILS_ENV" != "test" ]] && bundle exec rails s -p 3000 -b "0.0.0.0"'
  volumes:
    - .:/myapp
  ports:
      - "3000:3000"
  links:
    - db:db
